[package]
name = "str-util"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[dependencies]
smol_str.workspace = true

[features]
serde = ["smol_str/serde"]
