[package]
name = "event-parse"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
drop_bomb = "0.1"
token = { path = "../token" }
rowan = { version = "0.15", optional = true }

[features]
default = ["rowan"]
