[package]
name = "pattern-match"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[lints]
workspace = true

[dependencies]
fast-hash.path = "../fast-hash"
