[package]
name = "text-pos"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
line-index.workspace = true

text-size-util.path = "../text-size-util"
