[package]
name = "text-pos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false

[dependencies]
fast-hash = { path = "../fast-hash" }
text-size-util = { path = "../text-size-util" }
