[package]
name = "text-pos"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false

[dependencies]
line-index = "=0.1.0-pre.1"

text-size-util = { path = "../text-size-util" }
