[package]
name = "paths"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
nohash-hasher.workspace = true

fast-hash.path = "../fast-hash"
idx.path = "../idx"
str-util.path = "../str-util"
