[package]
name = "paths"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false
doctest = false

[dependencies]
glob = "0.3.1"
nohash-hasher = "0.2"

fast-hash = { path = "../fast-hash" }
idx = { path = "../idx" }
str-util = { path = "../str-util" }
