[package]
name = "write-rs-tokens"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false

[dependencies]
prettyplease.workspace = true
proc-macro2.workspace = true
syn.workspace = true
