[package]
name = "syntax-gen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false

[dependencies]
char-name = { path = "../char-name" }
fast-hash = { path = "../fast-hash" }
identifier-case = { path = "../identifier-case" }
proc-macro2 = "1.0.63"
quote = "1.0.29"
ungrammar = "1.16.1"
