[package]
name = "syntax-gen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
test = false

[dependencies]
proc-macro2 = "1"
quote = "1"
rustc-hash = "1"
ungrammar = "1"
identifier-case = { path = "../identifier-case" }
