[package]
name = "text-size-util"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[lints]
workspace = true

[dependencies]
text-size.workspace = true
