[package]
name = "fast-hash"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
test = false
doctest = false

[lints]
workspace = true

[dependencies]
rustc-hash.workspace = true
