[package]
name = "chain-map"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
fast-hash.path = "../fast-hash"
str-util.path = "../str-util"

[features]
sync = []
