[package]
name = "uri-db"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false
test = false

[dependencies]
url = "2.4.0"

fast-hash = { path = "../fast-hash" }
