[package]
name = "uri-db"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
doctest = false
test = false

[dependencies]
url = "2.4.0"

fast-hash = { path = "../fast-hash" }
