[package]
name = "apply-changes"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
text-pos.path = "../text-pos"
